/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.copycenter.ui.operatorUI;

import com.mycompany.copycenter.ui.UserInfoForm;
import com.mycompany.copycenter.ui.managerUI.OrderCreatorForm;
import com.mycompany.copycenter.ui.managerUI.OrderPaymentForm;

/**
 *
 * @author max19
 */
public class OperatorMenu extends javax.swing.JFrame {

    /**
     * Creates new form OperatorMenu
     */
    public OperatorMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profileButton = new javax.swing.JButton();
        getOrderButton = new javax.swing.JButton();
        currentOrdersButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        profileButton.setText("Show profile");
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });

        getOrderButton.setText("Get order");
        getOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getOrderButtonActionPerformed(evt);
            }
        });

        currentOrdersButton.setText("Current orders");
        currentOrdersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentOrdersButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(getOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(profileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(currentOrdersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(profileButton)
                .addGap(49, 49, 49)
                .addComponent(getOrderButton)
                .addGap(47, 47, 47)
                .addComponent(currentOrdersButton)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
        new UserInfoForm().setVisible(true);
    }//GEN-LAST:event_profileButtonActionPerformed

    private void getOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getOrderButtonActionPerformed
        new OrderGettingForm().setVisible(true);
    }//GEN-LAST:event_getOrderButtonActionPerformed

    private void currentOrdersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentOrdersButtonActionPerformed
        new OrderGettingForm().setVisible(true);
        //форма схожая с получением заказа
        //логика на удаление из склада при выполнении
        //логика добавления выполненных заказов юзеру
    }//GEN-LAST:event_currentOrdersButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton currentOrdersButton;
    private javax.swing.JButton getOrderButton;
    private javax.swing.JButton profileButton;
    // End of variables declaration//GEN-END:variables
}
