package com.mycompany.copycenter.entity;
// Generated 23.03.2018 1:40:35 by Hibernate Tools 4.3.1



/**
 * CostId generated by hbm2java
 */
public class CostId  implements java.io.Serializable {


     private int materialsIdMaterials;
     private int typeIdType;

    public CostId() {
    }

    public CostId(int materialsIdMaterials, int typeIdType) {
       this.materialsIdMaterials = materialsIdMaterials;
       this.typeIdType = typeIdType;
    }
   
    public int getMaterialsIdMaterials() {
        return this.materialsIdMaterials;
    }
    
    public void setMaterialsIdMaterials(int materialsIdMaterials) {
        this.materialsIdMaterials = materialsIdMaterials;
    }
    public int getTypeIdType() {
        return this.typeIdType;
    }
    
    public void setTypeIdType(int typeIdType) {
        this.typeIdType = typeIdType;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CostId) ) return false;
		 CostId castOther = ( CostId ) other; 
         
		 return (this.getMaterialsIdMaterials()==castOther.getMaterialsIdMaterials())
 && (this.getTypeIdType()==castOther.getTypeIdType());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMaterialsIdMaterials();
         result = 37 * result + this.getTypeIdType();
         return result;
   }   


}


