package com.mycompany.copycenter.entity;
// Generated 23.03.2018 12:15:32 by Hibernate Tools 4.3.1



/**
 * Cost generated by hbm2java
 */
public class Cost  implements java.io.Serializable {


     private CostId id;
     private Materials materials;
     private Types types;
     private int sizePerOne;

    public Cost() {
    }

    public Cost(CostId id, Materials materials, Types types, int sizePerOne) {
       this.id = id;
       this.materials = materials;
       this.types = types;
       this.sizePerOne = sizePerOne;
    }
   
    public CostId getId() {
        return this.id;
    }
    
    public void setId(CostId id) {
        this.id = id;
    }
    public Materials getMaterials() {
        return this.materials;
    }
    
    public void setMaterials(Materials materials) {
        this.materials = materials;
    }
    public Types getTypes() {
        return this.types;
    }
    
    public void setTypes(Types types) {
        this.types = types;
    }
    public int getSizePerOne() {
        return this.sizePerOne;
    }
    
    public void setSizePerOne(int sizePerOne) {
        this.sizePerOne = sizePerOne;
    }




}


