package com.mycompany.copycenter.entity;
// Generated 21.03.2018 14:53:46 by Hibernate Tools 4.3.1



/**
 * Cost generated by hbm2java
 */
public class Cost  implements java.io.Serializable {


     private CostId id;
     private Materials materials;
     private Type type;
     private int sizePerOne;

    public Cost() {
    }

    public Cost(CostId id, Materials materials, Type type, int sizePerOne) {
       this.id = id;
       this.materials = materials;
       this.type = type;
       this.sizePerOne = sizePerOne;
    }
   
    public CostId getId() {
        return this.id;
    }
    
    public void setId(CostId id) {
        this.id = id;
    }
    public Materials getMaterials() {
        return this.materials;
    }
    
    public void setMaterials(Materials materials) {
        this.materials = materials;
    }
    public Type getType() {
        return this.type;
    }
    
    public void setType(Type type) {
        this.type = type;
    }
    public int getSizePerOne() {
        return this.sizePerOne;
    }
    
    public void setSizePerOne(int sizePerOne) {
        this.sizePerOne = sizePerOne;
    }




}


