package com.mycompany.copycenter.entity;
// Generated 23.03.2018 1:40:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Materials generated by hbm2java
 */
public class Materials  implements java.io.Serializable {


     private Integer idMaterials;
     private String name;
     private int quantity;
     private Set costs = new HashSet(0);

    public Materials() {
    }

	
    public Materials(String name, int quantity) {
        this.name = name;
        this.quantity = quantity;
    }
    public Materials(String name, int quantity, Set costs) {
       this.name = name;
       this.quantity = quantity;
       this.costs = costs;
    }
   
    public Integer getIdMaterials() {
        return this.idMaterials;
    }
    
    public void setIdMaterials(Integer idMaterials) {
        this.idMaterials = idMaterials;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public Set getCosts() {
        return this.costs;
    }
    
    public void setCosts(Set costs) {
        this.costs = costs;
    }




}


