package com.mycompany.copycenter.entity;
// Generated 23.03.2018 1:40:35 by Hibernate Tools 4.3.1



/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private int idOrder;
     private Types types;
     private Users users;
     private int size;
     private float price;
     private String clientName;
     private String clientPhone;
     private String orderStatus;

    public Orders() {
    }

	
    public Orders(int idOrder, Types types, int size, float price, String orderStatus) {
        this.idOrder = idOrder;
        this.types = types;
        this.size = size;
        this.price = price;
        this.orderStatus = orderStatus;
    }
    public Orders(int idOrder, Types types, Users users, int size, float price, String clientName, String clientPhone, String orderStatus) {
       this.idOrder = idOrder;
       this.types = types;
       this.users = users;
       this.size = size;
       this.price = price;
       this.clientName = clientName;
       this.clientPhone = clientPhone;
       this.orderStatus = orderStatus;
    }
   
    public int getIdOrder() {
        return this.idOrder;
    }
    
    public void setIdOrder(int idOrder) {
        this.idOrder = idOrder;
    }
    public Types getTypes() {
        return this.types;
    }
    
    public void setTypes(Types types) {
        this.types = types;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public int getSize() {
        return this.size;
    }
    
    public void setSize(int size) {
        this.size = size;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public String getClientName() {
        return this.clientName;
    }
    
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }
    public String getClientPhone() {
        return this.clientPhone;
    }
    
    public void setClientPhone(String clientPhone) {
        this.clientPhone = clientPhone;
    }
    public String getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }




}


