package com.mycompany.copycenter.entity;
// Generated 21.03.2018 14:53:46 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Order generated by hbm2java
 */
public class Order  implements java.io.Serializable {


     private int idOrder;
     private Type type;
     private User user;
     private int size;
     private Date term;
     private float price;
     private String clientName;
     private String clientPhone;
     private String orderStatus;

    public Order() {
    }

	
    public Order(int idOrder, Type type, int size, Date term, float price, String orderStatus) {
        this.idOrder = idOrder;
        this.type = type;
        this.size = size;
        this.term = term;
        this.price = price;
        this.orderStatus = orderStatus;
    }
    public Order(int idOrder, Type type, User user, int size, Date term, float price, String clientName, String clientPhone, String orderStatus) {
       this.idOrder = idOrder;
       this.type = type;
       this.user = user;
       this.size = size;
       this.term = term;
       this.price = price;
       this.clientName = clientName;
       this.clientPhone = clientPhone;
       this.orderStatus = orderStatus;
    }
   
    public int getIdOrder() {
        return this.idOrder;
    }
    
    public void setIdOrder(int idOrder) {
        this.idOrder = idOrder;
    }
    public Type getType() {
        return this.type;
    }
    
    public void setType(Type type) {
        this.type = type;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public int getSize() {
        return this.size;
    }
    
    public void setSize(int size) {
        this.size = size;
    }
    public Date getTerm() {
        return this.term;
    }
    
    public void setTerm(Date term) {
        this.term = term;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public String getClientName() {
        return this.clientName;
    }
    
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }
    public String getClientPhone() {
        return this.clientPhone;
    }
    
    public void setClientPhone(String clientPhone) {
        this.clientPhone = clientPhone;
    }
    public String getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }




}


