package com.mycompany.copycenter.entity;
// Generated 21.03.2018 14:53:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Type generated by hbm2java
 */
public class Type  implements java.io.Serializable {


     private Integer idType;
     private String name;
     private Set costs = new HashSet(0);
     private Set orders = new HashSet(0);

    public Type() {
    }

	
    public Type(String name) {
        this.name = name;
    }
    public Type(String name, Set costs, Set orders) {
       this.name = name;
       this.costs = costs;
       this.orders = orders;
    }
   
    public Integer getIdType() {
        return this.idType;
    }
    
    public void setIdType(Integer idType) {
        this.idType = idType;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getCosts() {
        return this.costs;
    }
    
    public void setCosts(Set costs) {
        this.costs = costs;
    }
    public Set getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set orders) {
        this.orders = orders;
    }




}


