/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.copycenter.ui.uiOperator;

import com.mycompany.copycenter.tools.Messanger;
import com.mycompany.copycenter.tools.interfaces.MessangerMenu;
import com.mycompany.copycenter.ui.models.OrderFinisherModel;
import com.mycompany.copycenter.ui.models.OrderGettingModel;
import com.mycompany.copycenter.ui.OrdersTableFrame;
import com.mycompany.copycenter.ui.UserInfoFrame;

/**
 *
 * @author max19
 */
public class OperatorMenu extends javax.swing.JFrame implements MessangerMenu{

    /**
     * Creates new form OperatorMenu
     */
    public OperatorMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profileButton = new javax.swing.JButton();
        getOrderButton = new javax.swing.JButton();
        orderFinisherButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        msgArea = new javax.swing.JTextArea();
        refreshMsgButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        profileButton.setText("Show profile");
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });

        getOrderButton.setText("Get order");
        getOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getOrderButtonActionPerformed(evt);
            }
        });

        orderFinisherButton.setText("Finish Order");
        orderFinisherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderFinisherButtonActionPerformed(evt);
            }
        });

        msgArea.setColumns(20);
        msgArea.setRows(5);
        jScrollPane1.setViewportView(msgArea);
        Messanger msg  = new Messanger("operator");
        msgArea.setText(msg.getMsgText());

        refreshMsgButton.setText("Refresh messages");
        refreshMsgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshMsgButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(getOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(profileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orderFinisherButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(refreshMsgButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(profileButton)
                .addGap(49, 49, 49)
                .addComponent(getOrderButton)
                .addGap(45, 45, 45)
                .addComponent(orderFinisherButton)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshMsgButton)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
        new UserInfoFrame().setVisible(true);
    }//GEN-LAST:event_profileButtonActionPerformed

    private void getOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getOrderButtonActionPerformed
        new OrdersTableFrame(this, new OrderGettingModel()).setVisible(true);
    }//GEN-LAST:event_getOrderButtonActionPerformed

    private void orderFinisherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderFinisherButtonActionPerformed
        new OrdersTableFrame(this, new OrderFinisherModel()).setVisible(true);
    }//GEN-LAST:event_orderFinisherButtonActionPerformed

    private void refreshMsgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshMsgButtonActionPerformed
        this.updateMsgArea();
    }//GEN-LAST:event_refreshMsgButtonActionPerformed

    @Override
    public void updateMsgArea(){
        Messanger msg  = new Messanger("operator");
        msgArea.setText(msg.getMsgText());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton getOrderButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea msgArea;
    private javax.swing.JButton orderFinisherButton;
    private javax.swing.JButton profileButton;
    private javax.swing.JButton refreshMsgButton;
    // End of variables declaration//GEN-END:variables
}
