/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.copycenter.ui.uiAccounter;

import com.mycompany.copycenter.ui.UserInfoFrame;

/**
 *
 * @author max19
 */
public class AccountantMenu extends javax.swing.JFrame {

    /**
     * Creates new form AccounterMenu
     */
    public AccountantMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salariesButton = new javax.swing.JButton();
        materialsButton = new javax.swing.JButton();
        costsButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();
        typesLabel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        salariesButton.setText("Account salaries");
        salariesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salariesButtonActionPerformed(evt);
            }
        });

        materialsButton.setText("Account materials");
        materialsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialsButtonActionPerformed(evt);
            }
        });

        costsButton.setText("Show costs");
        costsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costsButtonActionPerformed(evt);
            }
        });

        profileButton.setText("Show profile");
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });

        typesLabel.setText("Acccount types");
        typesLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typesLabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(materialsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salariesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(costsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(typesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(profileButton)
                .addGap(37, 37, 37)
                .addComponent(typesLabel)
                .addGap(44, 44, 44)
                .addComponent(salariesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(materialsButton)
                .addGap(48, 48, 48)
                .addComponent(costsButton)
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salariesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salariesButtonActionPerformed
        new SalariesTableFrame().setVisible(true);
    }//GEN-LAST:event_salariesButtonActionPerformed

    private void costsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costsButtonActionPerformed

    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
        new UserInfoFrame().setVisible(true);
    }//GEN-LAST:event_profileButtonActionPerformed

    private void materialsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialsButtonActionPerformed
        new MaterialsTableFrame().setVisible(true);
    }//GEN-LAST:event_materialsButtonActionPerformed

    private void typesLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typesLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typesLabelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton costsButton;
    private javax.swing.JButton materialsButton;
    private javax.swing.JButton profileButton;
    private javax.swing.JButton salariesButton;
    private javax.swing.JButton typesLabel;
    // End of variables declaration//GEN-END:variables
}
