/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.copycenter.ui.uiAccounter;

import com.mycompany.copycenter.ui.models.CostsModel;

/**
 *
 * @author max19
 */
public class CostsFrame extends javax.swing.JFrame {
  
    private final CostsModel model = new CostsModel();
    
    /**
     * Creates new form CostsFrame
     */
    public CostsFrame() {
        init();
    }
    
    private void init(){
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        electricityLabel = new javax.swing.JLabel();
        leaseLabel = new javax.swing.JLabel();
        materialsLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        eleCostField = new javax.swing.JTextField();
        leaseCostField = new javax.swing.JTextField();
        materialsCostField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        totalCostField = new javax.swing.JTextField();
        salariesCostField = new javax.swing.JTextField();
        salariesLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        electricityLabel.setText("Electricity");

        leaseLabel.setText("Lease");

        materialsLabel.setText("Materials");

        jButton1.setText("Pay off");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        eleCostField.setEditable(false);
        eleCostField.setText(model.getEleCost());

        leaseCostField.setEditable(false);
        leaseCostField.setText(model.getLeaseCost());

        materialsCostField.setEditable(false);
        materialsCostField.setText(model.getMaterialCost());

        jLabel4.setText("Total");

        totalCostField.setEditable(false);
        totalCostField.setText(model.getTotalCost());

        salariesCostField.setEditable(false);
        salariesCostField.setText(model.getSalariesCost());

        salariesLabel.setText("Salaries");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(materialsLabel)
                    .addComponent(leaseLabel)
                    .addComponent(electricityLabel)
                    .addComponent(jLabel4)
                    .addComponent(salariesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(salariesCostField)
                    .addComponent(eleCostField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(leaseCostField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(totalCostField)
                    .addComponent(materialsCostField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jButton1)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(electricityLabel)
                    .addComponent(eleCostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leaseLabel)
                    .addComponent(leaseCostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(materialsLabel)
                    .addComponent(materialsCostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salariesLabel)
                    .addComponent(salariesCostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(totalCostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        model.payOff();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eleCostField;
    private javax.swing.JLabel electricityLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField leaseCostField;
    private javax.swing.JLabel leaseLabel;
    private javax.swing.JTextField materialsCostField;
    private javax.swing.JLabel materialsLabel;
    private javax.swing.JTextField salariesCostField;
    private javax.swing.JLabel salariesLabel;
    private javax.swing.JTextField totalCostField;
    // End of variables declaration//GEN-END:variables
}
